---
title: "R Notebook"
output: html_notebook
---

```{r}
library(plotly)
head(iris)
iris=datasets::iris
```


```{r}
plot_ly(data=iris,x=~Sepal.Length,y=~Petal.Length,mode="markers",marker=list(size=10,color='rgba(255,170,190,.9)'))
```


```{r}
plot_ly(data=iris,x=~Sepal.Length,y=~Petal.Length,mode="markers",marker=list(size=10,color='rgba(255,170,190,.9)',line=list(color='rgba(200,0,0,0.9)',width=2)))
```

```{r}
plot_ly(data=iris,x=~Sepal.Length,y=~Petal.Length,mode="markers",color=species
```


```{r}
library(RColorBrewer)
plot_ly(data=iris,x=~Sepal.Length,y=~Petal.Length,mode="markers",
        color=~Species,colors = "Spectral")
```

```{r}
library(RColorBrewer)
plot_ly(data=iris,x=~Sepal.Length,y=~Petal.Length,mode="markers",
        color=~Species,colors = "Dark2")
```

```{r}
library(RColorBrewer)
col<-c("red","blue","green")
plot_ly(data=iris,x=~Sepal.Length,y=~Petal.Length,mode="markers",
        color=~Species,colors = col)
```


```{r}
library(RColorBrewer)
col<-c("red","blue","green")
col<-setNames(col,c("virginica","setosa","versicolor"))

plot_ly(data=iris,x=~Sepal.Length,y=~Petal.Length,mode="markers",
        color=~Species,colors = col)
```

```{r}
library(RColorBrewer)
col<-c("red","blue","green")
col<-setNames(col,c("virginica","setosa","versicolor"))

plot_ly(data=iris,x=~Sepal.Length,y=~Petal.Length,mode="markers",
        color=~Species,colors = col,symbol=~Species)
```

```{r}
library(RColorBrewer)
col<-c("red","blue","green")
col<-setNames(col,c("virginica","setosa","versicolor"))

plot_ly(data=iris,x=~Sepal.Length,y=~Petal.Length,mode="markers",
        color=~Species,colors = col,symbol=~Species,symbols = c('pentagon','x','o'))
```

```{r}
library(RColorBrewer)
col<-c("red","blue","green")
col<-setNames(col,c("virginica","setosa","versicolor"))

plot_ly(data=iris,x=~Sepal.Length,y=~Petal.Length,mode="markers",marker=list(size=10),
        color=~Species,colors = col,symbol=~Species,symbols = c('pentagon','x','o'))
```


```{r}
library(RColorBrewer)
col<-c("red","blue","green")
col<-setNames(col,c("virginica","setosa","versicolor"))

plot_ly(data=iris,x=~Sepal.Length,y=~Petal.Length,mode="markers",
        color=~Species,text=~paste("width:",Sepal.Width),colors = col,symbol=~Species,symbols = c('pentagon','x','o'))
```


```{r}
day<-c(1:30)
num<-rnorm(30,mean=3)
df<-data.frame(day,num)
df
```
```{r}
plot_ly(df,x=~day,y=~num,type="scatter",mode="lines")
```


```{r}
plot_ly(df,x=~day,y=~num,type="scatter",mode="lines+markers")
```

```{r}
plot_ly(df,x=~day,y=~num,type="scatter",mode="lines+markers",line=list(color='red'))
```

```{r}
plot_ly(df,x=~day,y=~num,type="scatter",mode="lines+markers",line=list(color='red',width=4))
```

```{r}
plot_ly(df,x=~day,y=~num,type="scatter",mode="lines+markers",line=list(color='red',width=4,dash='dash'))
```

```{r}
plot_ly(df,x=~day,y=~num,type="scatter",mode="lines+markers",line=list(color='red',width=4,dash='dot'))
```

```{r}
library(ggplot2)
p=ggplot(iris,aes(x=Sepal.Length,y=Petal.Length))+geom_point()
p
```

#to convert ggplot to interactive plotly
```{r}

p=ggplot(iris,aes(x=Sepal.Length,y=Petal.Length))+geom_point()
ggplotly(p)
```

```{r}
fruits<-c("apple","banana","orange")
count_c<-c(200,150,300)
count_b<-c(100,250,150)
df1<-data.frame(fruits,count_b,count_c)
plot_ly(df1,x=~fruits,y=~count_c,type="bar")
```

```{r}
fruits<-c("apple","banana","orange")
count_c<-c(200,150,300)
count_b<-c(100,250,150)
df1<-data.frame(fruits,count_b,count_c)
p=plot_ly(df1,x=~fruits,y=~count_c,type="bar")
p<-p%>%add_trace(y=~count_b)
p=p%>%layout(barmode="group") #barmode="stack"
p
```

```{r}

```






