---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(ggplot2)
library(plotly)
```

```{r}
msleep
```

```{r}
cat(factor(msleep$order))
```

## Pie-Chart
```{r}
df_order = data.frame(table(msleep$order))
print(df_order)
```

```{r}

fig_order = plot_ly(type='pie', labels=df_order$Var1, values=df_order$Freq, 
                    textinfo='label+percent',insidetextorientation='radial')
fig_order
```


```{r}
df_vore = data.frame(table(msleep$vore))
df_vore
```


```{r}
fig_vore = plot_ly(type='pie', labels=df_vore$Var1, values=df_vore$Freq,
                   textinfo='label+percent',insidetextorientation='radial')
fig_vore
```

## Scatter plot
```{r}
fig_sp = plot_ly(data = msleep, x=~brainwt, y=~bodywt, color = ~order)
fig_sp
```

### Using Normalization
```{r}
plot(sqrt(msleep$bodywt), sqrt(msleep$brainwt), col="red")
text(sqrt(msleep$bodywt), sqrt(msleep$brainwt), msleep$name, cex=0.5)
```

```{r}
plot(msleep$bodywt^(1/100), msleep$brainwt^(1/100), col="red")
text(msleep$bodywt^(1/100), msleep$brainwt^(1/100), msleep$name, cex=0.5)
```

## Scatter plot
```{r}
plot(log10(msleep$bodywt), log10(msleep$brainwt), col="red")
text(log10(msleep$bodywt), log10(msleep$brainwt), msleep$name, cex=0.5)
```

```{r}
t <- list(family = "Helvetica",size = 14,color = "blue")
t1 <- list(family = "Times New Roman",color = "red")
t2 <- list(family = "Courier New",size = 14,color = "green")
t3 <- list(family = 'Arial')
```

```{r}
fig_sp = plot_ly(data = msleep, x = ~log10(bodywt), y = ~log10(brainwt), color = ~name,
                  type = 'scatter', mode = 'markers')%>%
                          layout(title= list(text = "Body weight vs Brain weight",font = t1), font=t, 
                          legend = list(title=list(text='Animals',font = t2)), 
                          xaxis  = list(title = list(text ='Brain Weight', font = t3)),
                          yaxis  = list(title = list(text ='Body Weight', font = t3)),
                          plot_bgcolor='#e5ecf6')

fig_sp
```
This is shows a clear linear relation-ship between Body weight and Brain weight

## Barplot
```{r}
# Define labels for the bars
labs = c('herbi'='Herbivore',
         'carni'='Carnivore',
         'omni'='Omnivore',
         'insecti'='Insectivore')

bar_plot = ggplot(data=msleep, aes(x = vore, y = ..count.. / sum(..count..),fill = factor(vore))) + 
           geom_bar(color='black') +
           labs(x = "Vore", y = "Percentage of Vore", title  = "Percentage of the quality of the Vore") +
           scale_x_discrete(labels =labs)
           scale_y_continuous(labels = scales::percent)

ggplotly(bar_plot)
```
## Histogram
```{r}
histogram_plot = ggplot(data=msleep, aes(x = sleep_total)) + 
                 geom_histogram(binwidth = 1.25, color = "black",fill = "grey") +
                 labs(x = "Total Time asleep per day(h)", y="Count", title="Count of Total Time asleep per day(h)") +
                 scale_x_discrete(labels =labs)

ggplotly(histogram_plot)

```

## Kernel Density Plot
```{r}
density_plot = ggplot(data=msleep, aes(x =log10(brainwt))) +
               geom_density(fill = "indianred3") + 
               labs(x = "brain weight", y="density", title="Kernal density of the brain weight")

ggplotly(density_plot)
```


```{r}
```


```{r}
```


