---
title: "R Notebook"
output: html_notebook
---

## Importing the libraries
```{r}
library(tidyverse)
library(plotly)
```

## Importing the data-set
```{r}
# National Parks in California
ca = read_csv("https://raw.githubusercontent.com/ScienceParkStudyGroup/r-lesson-based-on-ohi-data-training/gh-pages/data/ca.csv") 

head(ca)
```

```{r}
# Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/ScienceParkStudyGroup/r-lesson-based-on-ohi-data-training/gh-pages/data/acadia.csv")

head(acadia)
```

```{r}

# Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/ScienceParkStudyGroup/r-lesson-based-on-ohi-data-training/gh-pages/data/se.csv")

head(se)
```

```{r}
# 2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/ScienceParkStudyGroup/r-lesson-based-on-ohi-data-training/gh-pages/data/visit_16.csv")

head(visit_16)
```

```{r}
# All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/ScienceParkStudyGroup/r-lesson-based-on-ohi-data-training/gh-pages/data/mass.csv")

head(mass)
```

## Plot-2 --> ggplot
### Scatter plot
```{r}
scatter_plot = plot_ly(data=ca, x=~year, y=~visitors,color = ~park_name, type='scatter',mode='markers') %>%
                       layout(
                          title= list(text = "<b>Body weight vs Brain weight"),
                          legend = list(title = list(text ='<b>Animals')), 
                          xaxis  = list(title = list(text ='<b>Brain Weight')),
                          yaxis  = list(title = list(text ='<b>Body Weight')))
scatter_plot
```

### Barchart
```{r}
r_group_barchart = data.table::melt(ca, id.vars='park_name') %>%
plot_ly(x = ~park_name, y = ~value, type = 'bar', name = ~variable, color = ~variable) %>%
      layout(
          title= list(text = "<b>Total Distribution based on Vore"),
          legend = list(title = list(text= '<b>Aniamal Feature')),
          xaxis  = list(title = list(text ='<b>Vores')),
          yaxis = list(title='Count', text='<b>Count'), barmode = 'group')
r_group_barchart
```
### pie-chart
```{r}
df_order = data.frame(table(ca$park_name))
df_order
```

```{r}
pie_chart = plot_ly(type='pie', labels=df_order$Var1, values=df_order$Freq, 
                    textinfo='label+percent',insidetextorientation='radial') %>%
                    layout(
                          title= list(text = "<b>Order Distributions"),
                          legend = list(title = list(text= '<b>Order')))

pie_chart
```

```{r}
histogram_plot = plot_ly(data = ca, x = ~(log(visitors)), name=~code,type="histogram") %>%
                  layout(
                          title= list(text = "<b>Total sleep time of Animals based on Vore"),
                          legend = list(title = list(text= '<b>Vore')),
                          xaxis  = list(title = list(text ='<b>Visitors')),
                          yaxis  = list(title = list(text ='<b>Count')))
histogram_plot
```

### Donut Chart / Open Pie-Chart
```{r}
df_vore = data.frame(table(ca$code))
df_vore
```

```{r}
donut_chart = plot_ly(labels=df_vore$Var1, values=df_vore$Freq, 
                    textinfo='label+percent') %>%
                    add_pie(hole = 0.6) %>%
                    layout(
                          title= list(text = "<b>Order Distributions"),
                          legend = list(title = list(text= '<b>Order')))

donut_chart
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```


```{r}
```


```{r}
```
