---
title: "R Notebook"
output: html_notebook
---

## Importing the libraries
```{r}
library(tidyverse)
library(plotly)
library(ggplot2)
require(devtools)
library(dplyr)
library(tidyverse)
```

## Importing the data-set
```{r}
# National Parks in California
df = read_csv("zomato.csv")
head(df)
```

## Analysing the data-type of the data
```{r}
colnames(df)
```

```{r}
str(df)
```

```{r}
bar_plot = ggplot(data=df, aes(x = `Rating.color`, y = ..count.. / sum(..count..),fill = factor(`Rating.color`))) +
           geom_bar(color='black') + 
           labs(x = "National Parks", y = "Percentage of National Parks in the data-set", 
                title = "Occurence of the National Parks in the data-set") +
  
           scale_y_continuous(labels = scales::percent)
           
bar_plot + coord_flip()

```

```{r}
df %>%
  filter(`Country Code` == 1) %>%
  select(`Restaurant ID`) %>%
  unique() %>%
  nrow()
```
There are 8652 restaurants operating in India

```{r}
df %>% filter(`Country Code` == 1) %>% select(`Restaurant ID`,`City`) %>% unique() %>% group_by(`City`) %>% summarise(n=n()) %>%
  ggplot(aes(x=reorder(`City`,n),y=n))+ geom_bar(stat = 'identity',fill='#cb202d')+
  coord_flip() +
  theme(panel.background = element_blank(),
        strip.background = element_blank(),
        axis.title = element_text(color = '#2d2d2d'),
        strip.text.x = element_text(color='#2d2d2d',face='bold',size=10),
        plot.title = element_text(hjust=0.5,face='bold',size=15))+
        labs(x='City',y='Number of Restaurants',title="Number of Restaurants by City")
```
There are more restaurants in Delhi which operates with Zomato
```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
